services:
  db:
    image: postgis/postgis:17-3.5
    container_name: numad-db
    environment:
      POSTGRES_USER: numad
      POSTGRES_PASSWORD: numad
      POSTGRES_DB: numad
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U numad -d numad"]
      interval: 5s
      timeout: 5s
      retries: 5

  import:
    container_name: numad-import
    build: 
      context: import/
      dockerfile: Dockerfile
    volumes:
      - ./data:/data
      - import-venv:/app/.venv
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: tail -f /dev/null

  kottster:
    build:
      context: kottster
      dockerfile: Dockerfile
    container_name: numad-kottster
    ports:
      - "5480:5480"
      - "5481:5481"
    volumes:
      - ./kottster:/app
      - /app/node_modules
    environment:
      - PORT=5480
      - DEV_API_SERVER_PORT=5481
      - VITE_DOCKER_MODE=true
      - DATABASE_URL=postgresql://numad:numad@db:5432/numad
    tty: true
    stdin_open: true
    command: tail -f /dev/null
    depends_on:
      db:
        condition: service_healthy

volumes:
  import-venv:
  pgdata:
    name: numad_pgdata
