name: belhisfirm-sampo

services:

  # NGINX Cache Layer for Ontop
  cache:
    image: nginx:1.29.5-alpine
    network_mode: host
    volumes:
      - ./cache:/etc/nginx/templates
    environment:
      - CACHE_ENDPOINT=https://data.belhisfirm.be
      - CACHE_HOST=data.belhisfirm.be
      - CACHE_DURATION=24h
      - CACHE_MAX_SIZE=2g
      - CACHE_HTTP_PORT=8099

  # Sampo UI - Client
  client:
    image: ghcr.io/ghentcdh/sampo-ui-client:latest
    container_name: sampo-ui-client-prod
    network_mode: host
    environment:
      API_URL: ${API_URL}

  # Sampo UI - Server
  server:
    image: sampo-ui-server:prod
    container_name: sampo-ui-server-prod
    network_mode: host
    environment:
      SPARQL_ENDPOINT: ${SPARQL_ENDPOINT}
    volumes:
      - ./sampo/configs:/app/configs